shellcheck:
    tags:
        - shellcheck
    before_script:
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz"
        - tar -xvf shellcheck-latest.linux.x86_64.tar.xz
        - cp --remove-destination shellcheck-latest/shellcheck /usr/local/bin/
    script: /usr/bin/shellcheck esp

source_test:
    tags:
        - source
    before_script:
        - TERM=xterm-256color
        - TECH=r.grassmuck
        - SSP=0
        - export TERM TECH SSP
        - mkdir /var/cpanel
    script: 
        - source esp
    after_script:
        - rmdir /var/cpanel