image: alpine:latest

before_script:
    - apk add wget xz tar
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz"
    - tar -xvf shellcheck-latest.linux.x86_64.tar.xz
    - cp shellcheck-latest/shellcheck /usr/bin/

shellcheck:
    script: /usr/bin/shellcheck esp
