image: alpine:latest


shellcheck:
    tags:
        - shellcheck
    before_script:
        - apk add wget xz tar
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz"
        - tar -xvf shellcheck-latest.linux.x86_64.tar.xz
        - cp shellcheck-latest/shellcheck /usr/bin/
    script: /usr/bin/shellcheck esp

source_test:
    tags:
        - source
    before_script:
        - TERM=xterm-256color; export TERM
    script: 
        - /bin/bash source esp
